language: php

php:
  - 5.4
  - 5.5

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

install:
- sudo apt-get install -y --force-yes php5-curl php5-intl memcached php5-memcached > /dev/null

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e 'create database slick_tests;'

script:
  - vendor/bin/codecept run --coverage --xml

after_script:
     - php vendor/bin/coveralls -v
