<?php

/**
 * Schema sql dump file
 *
 * @package   Test\Database\Schema
 * @author    Filipe Silva <silvam.filipe@gmail.com>
 * @copyright 2014 Filipe Silva
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 * @since     Version 1.1.0
 */

return "CREATE TABLE people (id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, CONSTRAINT peoplePrimary PRIMARY KEY (id), CONSTRAINT peopleUniqueEmail UNIQUE (email));CREATE TABLE credentials (id BIGINT NOT NULL AUTO_INCREMENT, username VARCHAR(255) NOT NULL, password VARCHAR(64) NOT NULL, person_id BIGINT NOT NULL, email VARCHAR(255) NOT NULL, CONSTRAINT credentialsPrimary PRIMARY KEY (id), CONSTRAINT credentialsUniqueUsername UNIQUE (username), CONSTRAINT credentialPersonFk FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE ON UPDATE NO ACTION);CREATE TABLE profiles (id BIGINT NOT NULL AUTO_INCREMENT, language VARCHAR(255) NOT NULL, timeZone VARCHAR(255) NOT NULL, picture VARCHAR(255) NOT NULL, person_id BIGINT NOT NULL, CONSTRAINT profilesPrimary PRIMARY KEY (id), CONSTRAINT profilePersonFk FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE ON UPDATE NO ACTION);CREATE TABLE tags (id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, CONSTRAINT tagsPrimary PRIMARY KEY (id), CONSTRAINT tagsUniqueName UNIQUE (name));CREATE TABLE posts (id BIGINT NOT NULL AUTO_INCREMENT, title VARCHAR(255) NOT NULL, body VARCHAR(16000) NOT NULL, created TIMESTAMP NOT NULL, person_id BIGINT, CONSTRAINT tagsPrimary PRIMARY KEY (id), CONSTRAINT postPersonFk FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL ON UPDATE NO ACTION);CREATE TABLE posts_tags (post_id BIGINT NOT NULL, tag_id BIGINT NOT NULL, CONSTRAINT tagsPostsPrimary PRIMARY KEY (post_id, tag_id), CONSTRAINT postsTagsPostFk FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT postsTagsTagFk FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE ON UPDATE NO ACTION);CREATE TABLE comments (id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(16000) NOT NULL, person_id BIGINT NOT NULL, post_id BIGINT NOT NULL, CONSTRAINT commentsPrimary PRIMARY KEY (id), CONSTRAINT commentsPostFk FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT commentsPersonFk FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE ON UPDATE NO ACTION)";